apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayapi-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayapi
  template:
    metadata:
      labels:
        app: gatewayapi
    spec:
      containers:
        - name: gatewayapi
          image: simonegeurtz/gateway:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "50Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "2000m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: { }
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: gatewayapi
  ports:
    - name: gatewayapi-port
      protocol: TCP
      port: 9090
      targetPort: 80
